### PR TITLE
Add support for --version in fake ruby.exe

### PR DESCRIPTION
**Pull request by lordlydon**

### CODE REVIEW

**Comment by ccmywish** [comment]
Hi @lordlydon 

Thanks for your patience in knowing the repo details and your commit.

As for this pull request, I'm not sure why we should add the support for `--version`. In the document [principle.md](https://github.com/ccmywish/rbenv-for-windows/blob/main/doc/principle.md), I've already assumed this is by design to only accept `-v`. It makes `starship` work well, do you have any other reasons?
https://github.com/ccmywish/rbenv-for-windows/blob/a93b24f6691c66ad614d2defd9acf70638c0b354/doc/principle.md?plain=1#L27-L34

**Comment by lordlydon** [comment]
Hey, sorry for the lack of details, I was testing the tool and noticed an error with my prompt [oh-my-posh](https://ohmyposh.dev/)

oh-my-posh uses the full "--version" instead of the "-v" shorthand, so it doesn't display the correct version (I get the fake ruby.exe message instead), this change is meant to fix that

This is my first time making a pr to an open-source repo, so let me know if I missed something or should add anything else

**Comment by ccmywish** [comment]
Great job👍 Thanks for your help! I'll merge your commit and release a new binary soon later.

**Comment by lordlydon** [comment]
It's working now, thank you!

**Pull request merged**
